[package]
name = "advance_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
cartesi-machine = { git = "https://github.com/cartesi/dave", branch = "main" }
reflink = "0.1.3"
alloy-sol-types = "0.7.2"
alloy-primitives = "0.7.2"