[package]
name = "advance_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
cartesi-machine = { git = "https://github.com/cartesi/dave", rev = "d3059a0d70535fb6a9757ee8c8f6170adcddee4e" }
reflink = "0.1.3"
alloy-sol-types = "0.7.2"
alloy-primitives = "0.7.2"